import fs from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export class ContextManager {
  private filePath: string;
  private historyPath: string;

  constructor(workspacePath: string) {
    this.filePath = path.join(workspacePath, '../PROJECT_CONTEXT.md');
    this.historyPath = path.join(workspacePath, '../PROJECT_HISTORY.md');
  }

  async updateContext(teamId?: string) {
    const teams = await prisma.team.findMany({ 
      include: { 
        members: { include: { agent: true } }, 
        tasks: { where: { status: { not: 'completed' } } },
        decisionLogs: { orderBy: { timestamp: 'desc' }, take: 5 }
      } 
    });
    const agents = await prisma.agent.findMany();

    const context = `
# PROJECT CONTEXT - ForgeLab
*Last Updated: ${new Date().toISOString()}*

## 🎯 Active Goals
${teams.map(t => `- Team: ${t.name} (Status: ${t.status})`).join('\n')}

## 🤖 Agent Assignments
${agents.filter(a => a.status !== 'idle').map(a => `- ${a.name} (${a.role})`).join('\n')}

## 💡 Recent Decisions
${teams.flatMap(t => t.decisionLogs).map(d => `- ${d.decision} (${new Date(d.timestamp).toLocaleDateString()})`).join('\n')}

## ⏳ Pending Approvals
${teams.flatMap(t => t.tasks.filter(task => task.status === 'waiting-for-approval')).map(t => `- ${t.title}`).join('\n')}

---
*Generated by ForgeLab ContextManager.*
`;
    fs.writeFileSync(this.filePath, context);
  }
}
